<a href="https://colab.research.google.com/github/Ekta194/clob_python/blob/main/Day_4_Review_co_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python Offers a variety of basic data types that we can do some basic operations on. Tinkering and experimenting with data comes highly recommended

In [ ]:
#strings
my_string = 'fdfsdfsdfsdfsfd'
another_string = 'some string'
#ints
my_int = 4
another_int = 347
#floats
my_float = 23.17
another_float = 71.9
#booleans
my_bool = True
another_bool = False
yet_another_bool = (4 == 6)

We can see the variety of built in method's to use on Strings:

In [ ]:


# Length of the string
#print(len(my_string))

# Accessing individual characters using indexing
#print(my_string[0])     # Output: 'f'
#print(another_string[5])  # Output: 's'

# Slicing a string
#print(my_string[2:14])     # Output: 'fds'
#print(another_string[0:])  # Output: 'me string'

# Concatenating strings
#concatenated = my_string + another_string
#print(concatenated)       # Output: 'fdfsdfsdfsdfsfdsome string'
#print('abc'+'def')
# Converting to uppercase or lowercase
#print(my_string.upper())    # Output: 'FDFSDFSDFSDFSFD'
#print('ASAFD!&'.lower())  #
#print("doijhgjh".title())
# Checking if a string starts or ends with a specific substring
#print(my_string.startswith('fdfa'))   # Output: True
#print(another_string.endswith('ing'))  # Output: True

# Splitting a string into a list of substrings
#split_string = another_string.split('m')
#print(split_string)      # Output: ['some', 'string']

# Replacing substrings
#replaced_string = my_string.replace('fd', 'xyz')
#print(replaced_string)   # Output: 'xyzsdfsdfsdfsxyzsfd'

# Finding the index of a substring
#print(another_string.index('some'))   # Output: 5

# Counting occurrences of a substring
print(my_string.count('sfd'))   # Output: 2


1


This method for counting occurences of a substring allows for a "rules-based" sentiment analysis of text.
Incidently this allows us to make good use of functions and if/else logic.

In [ ]:
def sentiment_detection(sentence):
  positive = False
  negative = False
  for i in ('happy', 'sunny', 'positive','triumphant','optimistic','wonderful'):
    if sentence.count(i) > 0:
      positive = True
  for i in ('sad','terrible','frightening','rainy','scary'):
    if sentence.count(i) > 0:
      negative = True
  if positive == negative == False:
    return "neutral"
  elif positive == True != negative:
    return "positive"
  elif negative == True != positive:
    return 'negative'
  else:
    return "mixed"

In [ ]:
sentiment_detection("It is rainy")

'negative'

We can run different methods on Ints

In [ ]:


# Converting an integer to a string
#print(str(my_int))       # Output: '4'
#print(str(another_int))  # Output: '347'

# Finding the absolute value
#print(abs(-5))           # Output: 5
#print(abs(-10.5))        # Output: 10.5

# Performing arithmetic operations
#print(my_int + another_int)  # Output: 351
#print(my_int * another_int)  # Output: 1388
#print(my_int / another_int)  # Output: 0.011507965444679398

# Checking if an integer is even or odd
#print(my_int % 2 == 0)       # Output: True
#print(another_int % 2 == 0)  # Output: False

# Checking if an integer is positive, negative, or zero
#print(my_int > 0)            # Output: True
#print(another_int < 0)       # Output: False
#print(my_int == 0)           # Output: False

# Raising an integer to a power
#print(my_int ** 2)           # Output: 16
#print(another_int ** 3)      # Output: 43046723
#print(my_int**(1/2))
#Checking if an integer is divisible by another integer
#print(another_int % 7 == 0)  # Output: True


False


We can run different methods on Floats

In [ ]:



# Rounding a float to a specified number of decimal places
#print(round(my_float, 1))              # Output: 23.2
#print(round(another_float, 2))         # Output: 71.9

# Getting the fractional and integer parts of a float
#print(3.0).is_integer())           # Output: False
#print((2.5).as_integer_ratio())     # Output: (2793604999065161, 1208925819614629174706176)
# print(another_float.as_integer_ratio())# Output: (5870264259746659, 8192)


# Converting a float to an integer (rounded towards zero)
# print(int(my_float))                   # Output: 23
# print(int(another_float))              # Output: 71


# Getting the absolute value of a float
# print(abs(my_float))                   # Output: 23.17
# print(abs(another_float))              # Output: 71.9

# Converting a float to a string with specific formatting
#print(format(my_float, '.2f'))         # Output: '23.17'
#print(format(another_float, '.1f'))    # Output: '71.9'

# Performing mathematical functions on floats
#import math
#print(math.sqrt(4))             # Output: 4.812618965552178
#print(math.sin(3.14/2))         # Output: -0.48514693710658093
#print(math.exp(my_float))              # Output: 6.897427948654809e+09



2.0
0.9999996829318346
11550562800.00226


There are a variety of methods and codes we can run with booleans that have surprising results

In [ ]:
# Boolean literals
#print(True)      # Output: True
# print(False)     # Output: False

# Boolean comparisons
# print(2 > 1)     # Output: True
# print(3 == 3.0)  # Output: True
#print(5 != 5)    # Output: False

# Boolean logical operators
#print(True and False)     # Output: False
#print(True or False)      # Output: True
# print(not True)           # Output: False


# Converting a boolean to an integer or string
#print(int(True))          # Output: 1
#print(int(False))         # Output: 0

#Math with Booleans
#print(True+True+False)
#print(True+True)
#print(True*3)
#print(True*False)

# Boolean operations with lists
my_list = [1, 2, 3]
#print(2 in my_list)       # Output: True
#print(4 in my_list)       # Output: False


# Boolean operations with sets
my_set = {1, 2, 3}
print(2 in my_set)        # Output: True
print(4 in my_set)        # Output: False




True
False


There is an efficient alternative to for-loops called comprehensions. The logic is very similar from a coding perspective, some consider the comprehensions more readable, and often times they may run faster.

In [ ]:
#for loop
numbers = [1, 2, 3, 4, 5]
squared_numbers = []
for num in numbers:
    squared_numbers.append(num ** 2)
print(squared_numbers)  # Output: [1, 4, 9, 16, 25]


[1, 4, 9, 16, 25]


In [ ]:
#comprehension
numbers = [1, 2, 3, 4, 5]
squared_numbers = [num ** 2 for num in numbers]
print(squared_numbers)  # Output: [1, 4, 9, 16, 25]



[1, 4, 9, 16, 25]


In [ ]:
#for loop
numbers = [1, 2, 3, 4, 5]
even_numbers = []
for num in numbers:
    if num % 2 == 0:
        even_numbers.append(num)
print(even_numbers)  # Output: [2, 4]


[2, 4]


In [ ]:
#comprehension
numbers = [1, 2, 3, 4, 5]
even_numbers = [num for num in numbers if num % 2 == 0]
print(even_numbers)  # Output: [2, 4]


[2, 4]


In [ ]:
#for loop
names = ['Alice', 'Bob', 'Charlie']
uppercase_names = []
for name in names:
    uppercase_names.append(name.upper())
print(uppercase_names)  # Output: ['ALICE', 'BOB', 'CHARLIE']


['ALICE', 'BOB', 'CHARLIE']


In [ ]:
#comprehension
names = ['Alice', 'Bob', 'Charlie']
uppercase_names = [name.upper() for name in names]
print(uppercase_names)  # Output: ['ALICE', 'BOB', 'CHARLIE']


['ALICE', 'BOB', 'CHARLIE']


As seen previously NumPy provides efficient ways for doing opperations on data that would otherwise be difficult. One of the biggest fundamental advantages of NumPy is how it '*vectorizes*' operations. Such operations don't require a lengthy process of iterating over a data-structure, but instead take advantage of low-level code where an operation may be applied to every element in a data-structure in parallel.

In [ ]:

# Using for-loops

a = [1, 2, 3]
b = [4, 5, 6]
result = []
for i in range(len(a)):
    result.append(a[i] * b[i])
print(result)  # Output: [4, 10, 18]


[4, 10, 18]


In [ ]:
# Using NumPy arrays
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a * b
print(result)  # Output: [4 10 18]

[ 4 10 18]


In [ ]:
# Using for-loops
import numpy as np

a = [1, 2, 3, 4, 5]
sum_result = 0
for num in a:
    sum_result += num
print(sum_result)  # Output: 15


15


In [ ]:
# Using NumPy arrays
import numpy as np

a = np.array([1, 2, 3, 4, 5])
sum_result = np.sum(a)
print(sum_result)  # Output: 15


15


In [ ]:
# Using for-loops
import numpy as np

a = [1, 2, 3, 4, 5]
result = []
for num in a:
    result.append(num ** 2)
print(result)  # Output: [1, 4, 9, 16, 25]


[1, 4, 9, 16, 25]


In [ ]:
# Using NumPy arrays
import numpy as np

a = np.array([1, 2, 3, 4, 5])
result = np.square(a)
print(result)  # Output: [ 1  4  9 16 25]


[ 1  4  9 16 25]


In [ ]:
# Using a for-loop
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]
result = []
for i in range(len(a)):
    result.append(a[i] + b[i])
print(result)

[7, 9, 11, 13, 15]


In [ ]:
# Using NumPy arrays
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
result = a + b
print(result)
result[0]

[ 7  9 11 13 15]


7

In [ ]:
# Using a for-loop
def multiply_list_by_constant(lst, constant):
    result = []
    for num in lst:
        result.append(num * constant)
    return result

numbers = [1, 2, 3, 4, 5]
constant = 2
result = multiply_list_by_constant(numbers, constant)
print(result)  # Output: [2, 4, 6, 8, 10]


[2, 4, 6, 8, 10]


In [ ]:
# Using NumPy arrays
import numpy as np

numbers = np.array([1, 2, 3, 4, 5])
constant = 2
result = numbers * constant
print(result)  # Output: [2 4 6 8 10]


[ 2  4  6  8 10]


Previously we saw a function using for-loops to do a rules-based sentiment analysis. Let's see how it can be optimized using comprehensions.

In [ ]:
def sentiment_detection(sentence):
    positive_words = ('happy', 'sunny', 'positive', 'triumphant', 'optimistic', 'wonderful')
    negative_words = ('sad', 'terrible', 'frightening', 'rainy', 'scary')

    positive = any(sentence.count(i) > 0 for i in positive_words)
    negative = any(sentence.count(i) > 0 for i in negative_words)

    if positive == negative == False:
        return "neutral"
    elif positive != negative:
        return "positive" if positive else "negative"
    else:
        return "mixed"


False

In [ ]:
positive_words = ('happy', 'sunny', 'positive', 'triumphant', 'optimistic', 'wonderful')
sentence = 'I am'
any(sentence.count(i) > 0 for i in positive_words)
#any([True])

False

Now a review of Pandas and it's built in techniques for data analysis

In [ ]:
import pandas as pd
import numpy as np

# Creating two DataFrames
df1 = pd.DataFrame({'ID': [1, 2, 3, 4],
                    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
                    'Age': [25, 30, 35, 40]})

df2 = pd.DataFrame({'ID': [1, 2, 3, 5],
                    'Salary': [50000, 60000, 70000, 80000]})

#CHALLENGE Next we will think of a way to do the merge so we don't lose any data.
# Merging DataFrames
merged_df = pd.merge(df1, df2, on='ID', how='left')
print(merged_df)
# Output:
#    ID     Name  Age   Salary
# 0   1    Alice   25  50000.0
# 1   2      Bob   30  60000.0
# 2   3  Charlie   35  70000.0
# 3   4    David   40      NaN



   ID     Name  Age   Salary
0   1    Alice   25  50000.0
1   2      Bob   30  60000.0
2   3  Charlie   35  70000.0
3   4    David   40      NaN


In [ ]:
#let's merge them so no data is lost


In [ ]:
# Creating a new column using a lambda function
merged_df['Age_Category'] = merged_df['Age'].apply(lambda x: 'Youth' if x < 30 else 'Adult')
print(merged_df)
# Output:
#    ID     Name  Age   Salary Age_Category
# 0   1    Alice   25  50000.0        Youth
# 1   2      Bob   30  60000.0        Adult
# 2   3  Charlie   35  70000.0        Adult
# 3   4    David   40      NaN        Adult

# Creating a new column using a NumPy function
merged_df['Age_Squared'] = np.square(merged_df['Age'])
print(merged_df)
# Output:
#    ID     Name  Age   Salary Age_Category  Age_Squared
# 0   1    Alice   25  50000.0        Youth          625
# 1   2      Bob   30  60000.0        Adult          900
# 2   3  Charlie   35  70000.0        Adult         1225
# 3   4    David   40      NaN        Adult         1600

   ID     Name  Age   Salary Age_Category
0   1    Alice   25  50000.0        Youth
1   2      Bob   30  60000.0        Adult
2   3  Charlie   35  70000.0        Adult
3   4    David   40      NaN        Adult
   ID     Name  Age   Salary Age_Category  Age_Squared
0   1    Alice   25  50000.0        Youth          625
1   2      Bob   30  60000.0        Adult          900
2   3  Charlie   35  70000.0        Adult         1225
3   4    David   40      NaN        Adult         1600


NumPy offers some amazing functions for handling different conditions

In [ ]:
data = {'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)

# Define the conditions
conditions = [
    df['A'] < 3,
    df['A'] >= 3,
]

# Define the functions corresponding to each condition
def function1(x):
    return x * 2

def function2(x):
    return x + 5

# Vectorize the functions
vectorized_function1 = np.vectorize(function1)
vectorized_function2 = np.vectorize(function2)

# Apply the functions based on the conditions and create the new column
df['C'] = np.select(conditions, [vectorized_function1(df['A']), vectorized_function2(df['B'])], default=np.nan)

# Display the updated DataFrame
print(df)

   A   B     C
0  1  10   2.0
1  2  20   4.0
2  3  30  35.0
3  4  40  45.0
4  5  50  55.0


In [ ]:
data = {'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)
df
# Define the conditions
conditions = [
    df['A'] < 3,
    df['A'] >= 3
]

# Define the functions corresponding to each condition
def function1(df):
    return df['A'] * 2 + df['B']

def function2(df):
    return df['A'] + df['B'] * 2

# Apply the functions based on the conditions and create the new column
df['C'] = np.select(conditions, [function1(df), function2(df)], default=np.nan)

# Display the updated DataFrame
print(df)

   A   B      C
0  1  10   12.0
1  2  20   24.0
2  3  30   63.0
3  4  40   84.0
4  5  50  105.0


Just like SQL, pandas also offers the option to group/aggregate data

In [ ]:
import pandas as pd

# Creating a sample DataFrame
data = {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C'],
    'Category': ['X', 'Y', 'Z', 'X', 'Y', 'Z'],
    'Sales': [100, 150, 200, 250, 300, 350]
}
df = pd.DataFrame(data)

# Grouping the DataFrame by 'Category' and calculating the total sales
grouped_df = df.groupby('Category').mean()

print(grouped_df)




          Sales
Category       
X         175.0
Y         225.0
Z         275.0


<ipython-input-132-5cbc87cee543>:12: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  grouped_df = df.groupby('Category').mean()
