<a href="https://colab.research.google.com/github/Ekta194/clob_python/blob/main/practice_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Functions/methods:






In [ ]:
import numpy as np
import pandas as pd

# Reshape an array
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (3, 2))
print(reshaped_arr)

# Transpose an array
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = np.transpose(arr)
print(transposed_arr)

# Concatenate two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print(concatenated_arr)

# Split an array into sub-arrays
arr = np.array([1, 2, 3, 4, 5, 6])
sub_arrays = np.split(arr, 3)
print(sub_arrays)

# Resize an array
arr = np.array([1, 2, 3])
resized_arr = np.resize(arr, (2, 2))
print(resized_arr)


[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[[1 2]
 [3 1]]


In [ ]:
import numpy as np

# Compute the exponential of array elements
arr = np.array([1, 2, 3])
exp_arr = np.exp(arr)
print(exp_arr)

# Compute the natural logarithI apologize for the incomplete response. Here are the remaining examples of mathematical functions:

# Compute the natural logarithm of array elements
arr = np.array([1, 2, 3])
log_arr = np.log(arr)
print(log_arr)

# Compute the sine of array elements
arr = np.array([0, np.pi/2, np.pi])
sin_arr = np.sin(arr)
print(sin_arr)

# Compute the cosine of array elements
cos_arr = np.cos(arr)
print(cos_arr)

# Compute the square root of array elements
arr = np.array([4, 9, 16])
sqrt_arr = np.sqrt(arr)
print(sqrt_arr)






[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[2. 3. 4.]


In [ ]:
# Reshape an array
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (2, 3))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Transpose an array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
transposed_arr = np.transpose(arr)
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Concatenate two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print(concatenated_arr)

[1 2 3 4 5 6]


In [ ]:
# Resize an array
arr = np.array([1, 2, 3])
resized_arr = np.resize(arr, (3, 5))
print(resized_arr)

[[1 2 3 1 2]
 [3 1 2 3 1]
 [2 3 1 2 3]]


Below is a demonstration of how pandas deals with strings mixed in with quantitative data.

In [ ]:
df = pd.DataFrame({'column 1': [6.5, 7.8, 9],'column 2':[5,8,10],'column 3':[5,8.2,'fifty-five']})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   column 1  3 non-null      float64
 1   column 2  3 non-null      int64  
 2   column 3  3 non-null      object 
dtypes: float64(1), int64(1), object(1)
memory usage: 200.0+ bytes


In [ ]:
type(df.iloc[2]['column 3'])

str

In the above scenario, the following implamentation simply won't work:

In [ ]:


# Example DataFrame
df = pd.DataFrame({'Number': ['1,000', '2,500', '3,750']})
df.info()
print(type(df.iloc[2]['Number']))
# Convert string-based column to float-based column
df['Number'] = df['Number'].str.replace(',', '').astype(float)

# Display the updated DataFrame
print(df)
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Number  3 non-null      object
dtypes: object(1)
memory usage: 152.0+ bytes
<class 'str'>
   Number
0  1000.0
1  2500.0
2  3750.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Number  3 non-null      float64
dtypes: float64(1)
memory usage: 152.0 bytes


We'll benefit from the following function:

In [ ]:
import re

def contains_non_numeric(string):
    pattern = r'[^0-9,.]'
    return re.search(pattern, string) is not None


In [ ]:
contains_non_numeric('fifty-five')


True

Or...

In [ ]:
int('9,00k00'.replace(',',''))

ValueError: ignored

Using a Lambda function on multiple rows simultaneously:

In [ ]:
import pandas as pd

data = {'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)

# Define the lambda function to operate on multiple columns
function = lambda row: row['A'] * 2 + row['B']

# Apply the lambda function to create the new column
df['C'] = df.apply(function, axis=1)

# Display the updated DataFrame
print(df)


   A   B   C
0  1  10  12
1  2  20  24
2  3  30  36
3  4  40  48
4  5  50  60


In [ ]:
import pandas as pd
import numpy as np

data = {'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)

# Define the conditions
conditions = [
    df['A'] < 3,
    df['A'] >= 3
]

# Define the functions corresponding to each condition
def function1(x):
    return x * 2

def function2(x):
    return x + 5

# Vectorize the functions
vectorized_function1 = np.vectorize(function1)
vectorized_function2 = np.vectorize(function2)

# Apply the functions based on the conditions and create the new column
df['C'] = np.select(conditions, [vectorized_function1(df['A']), vectorized_function2(df['B'])], default=np.nan)

# Display the updated DataFrame
print(df)


   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50


In [ ]:
import pandas as pd
import numpy as np

data = {'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)
df
# Define the conditions
conditions = [
    df['A'] < 3,
    df['A'] >= 3
]

# Define the functions corresponding to each condition
def function1(df):
    return df['A'] * 2 + df['B']

def function2(df):
    return df['A'] + df['B'] * 2

# Apply the functions based on the conditions and create the new column
df['C'] = np.select(conditions, [function1(df), function2(df)], default=np.nan)

# Display the updated DataFrame
print(df)


   A   B      C
0  1  10   12.0
1  2  20   24.0
2  3  30   63.0
3  4  40   84.0
4  5  50  105.0


In [ ]:
# Check if values in column 'A' are NaN
df['A'].isna()[3]


False